BiblioSitio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('src.urls')),
    path('admin/', admin.site.urls),
]

src/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name ="src"

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    
    path('login/', views.Login.as_view() ,name="login"),
    path('logout/', views.Logout.as_view() ,name="logout"),


    #Para los libros
    path('Libro_borrar/<int:pk>/', views.LibroEliminar.as_view() ,name="Libro_eliminar"),


    #Para pruebas
    path('pruebas/', views.pruebas ,name="pruebas"),
    path('registrar/', views.UsuariosCrear.as_view(), name ="registrar"),  

    #Para las apis
    #path('probando/', views.Probando ,name="probando"),
    path('api_login/', views.api_login ,name="api_login"),

    
    
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/models.py
import os
import shutil #libreria para borrar carpetas esten o no llenas
from django.conf import settings
from django.db import models

#Estos dos modelos son para crear permisos personalizados
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType


from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.dispatch import receiver
from django.db.models.signals import pre_save, post_save, pre_delete, post_delete


# Create your models here.

##################################################################################################
####################### Modelos para Usuarios ####################################################

class UsuarioManager(BaseUserManager):

    def create_user(self,email,username,password=None,admin = False,is_superuser =False,plan_elegido="gratis"):
        
        #if not email:
        #    raise ValueError('El usuario debe tener un correo electronico')

        usuario = self.model(
            
            username = username,
            email = self.normalize_email(email),
            password = password,
            #rol = rol,
            admin =admin,
            is_superuser = is_superuser,
            #plan_elegido = plan_elegido,
        )

        #aqui encriptamos la clave para no guardar en texto plano
        usuario.set_password(password)
        usuario.save()
        return usuario
    
    

    #Funcion para usuario administrador
    def create_superuser(self,email,username,password,admin = True,is_superuser = True):
        #print("Creamos superusuario")

        usuario = self.create_user(
            email = email,  
            username = username,
            #rol = rol,
            #plan_elegido = plan_elegido,
            password = password,
            admin =admin,
            is_superuser = is_superuser
        )
        
            
            
        print("Entramos en superuser")
        usuario.save()
        return usuario



# Heredamos de AbstractBaseUser para adaptarlo a nuestro gusto
class Usuarios(AbstractBaseUser,PermissionsMixin):

    #(Lo que se guarda en bases de datos, lo que se ve al usuario)
    usuario_tipos = [
        ('master','Master'),
    #    ('empresa','Empresa'),
    #    ('entrevistador','Entrevistador'),
    #    ('candidato','Candidato'),
        ('usuario','Usuario'),
    ]

    #tipo_plan = [
    #    ('gratis','Free'),
    #    ('pago','Pay'),
    #]
    
    
    username = models.CharField("Username",max_length=200,unique=True)
    nombres = models.CharField("Nombres",max_length=200,blank=True, null=True) 
    apellidos = models.CharField("Apellidos",max_length=200,blank=True, null=True) 
    email = models.EmailField("Correo Electronico",max_length=150, unique=True)
    activo = models.BooleanField(default=True)#Para poder ingresar al sistema  
    is_superuser = models.BooleanField(default=False)#Este es superusuario
    admin = models.BooleanField(default=False)#Para poder ingresar al admin de django
    cedula = models.IntegerField(default=0,blank=True, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True) 
    fecha_actualizacion = models.DateTimeField('actualizado', auto_now=True)
    direccion = models.CharField("Direccion",max_length=100,blank=True, null=True,default="Las Adjuntas") 
    telefono = models.CharField("Telefono", max_length=50,blank=True,null=True,default="04242020470")
    #imagen = models.ImageField("Imagen de perfil", upload_to="usuario/perfil", max_length=200,blank=True,null=True)
    
    #Para enlazar al manager que has creado
    objects = UsuarioManager()

    USERNAME_FIELD = 'username'  #Para estableccer este campo como unico
    REQUIRED_FIELDS = ['email','is_superuser'] # Campos obligatorios(los pide cuando los creas por consola)

    def __str__(self):
        return f'Usuario {self.username}'
    
    
    
    #para verificar si un usuario es administrador o no(Para entrar en el admin)
    @property
    def is_staff(self):
         # "Is the user a member of staff?"
         if self.activo:
            return self.admin
         return False
     

    def has_module_perms(self, app_label):
        return True



    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'
        db_table = 'usuarios'
        
        permissions = [
            #(Lo que se guarda en bases de datos, lo que se ve al usuario)
            #Permisos para master y gerente
            #("permisoscompletos", "Permisoscompletos"),
            
            
            
            
            
            
        ]#Fin de los permisos
        

class Libros(models.Model):
    
    id = models.BigAutoField(primary_key=True)
    nombre = models.CharField("Nombre",max_length=60,unique=True) 
    autor = models.CharField("Autor",max_length=50)

src/views.py
from urllib import response
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse, reverse_lazy
from .models import *
from django.shortcuts import redirect, render

#Clases para el login
from django.contrib.auth.views import LoginView, LogoutView
from .form import * #Asi importamos todos los formularios 


#Clases para las plantillas
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView, DeleteView




class Login(LoginView):

    template_name = "src/login.html"
    #template_name = "plantillas_viejas/login copy.html"
    form_class = loginForm

    def dispatch(self, request, *args, **kwargs):

        if request.user.is_authenticated:

            print("Estas autenticado y vas al INDEX.HTML")
            

        else:
            print(request.user)
            print("No estas autenticado, eres un usuario anonimo")
            return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #print("Metodo:",self.request.method)
        #print(self.form_class())
        #context['titulo'] = "Vouchly"
        #context['formRegistro'] = UsuariosForm(self.request.POST or None)
        return context





class Logout(LogoutView):

    template_name = "src/login.html"
    next_page = "src:login"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['informacion'] = "Hola..."
        return context
    



class UsuariosCrear(CreateView):


    model = Usuarios
    form_class = UsuariosForm
    template_name = "src/registrarUsuario.html"
    success_url = reverse_lazy('src:login') 

    def dispatch(self,request, *args, **kwargs):

        if self.request.method =="post":
            print("Vamos a guardar datos")

        return super().dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):

        print("Probando cosas...",self.request.method)
        context = super().get_context_data(**kwargs)
        context['informacion'] = "Hola..."
        context['titulo'] = "Create User"
        context['tituloBoton'] = "Save"
        context['usuario'] = self.request.user
        return context

    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        print("Entramos aqui en post de crear USUARIO")
        if form.is_valid():
            form.save()
            return redirect('src:index')
        else:
            print("\nHubo un error")
            print(form.errors)
            return render(request,"src/login.html",{'form':loginForm,'errores':form.errors})


        #return render(request, self.template_name, {'form': form})



class LibroEliminar(DeleteView):
    model = Libros
    template_name = "src/EliminarLibro.html"
    success_url = reverse_lazy('src:index') 

    def get_context_data(self, **kwargs):
        #print(self.object.id)
        context = super().get_context_data(**kwargs)
        context['informacion'] = "..."
        context['titulo'] = "Delete Libro"
        context['usuario'] = self.request.user
        return context


class Index(TemplateView):

    template_name = "src/index.html"

    def dispatch(self, request, *args, **kwargs):

        if request.user.is_anonymous:
            print("No estas autenticado, eres un usuario anonimo")
            return redirect("src:login")

        else:

            print("Estas autenticado GENIAL")
            
            form = LibrosForm()
            if request.method == "POST":
                print("Probando esta vaina> ",request.POST['autor'])
                form = LibrosForm(request.POST)
                if form.is_valid():
                    print("Valido")
                    #form.save()
                    #product = Product()
                    #product.title = form.cleaned_data['title']
                    #product.price = form.cleaned_data['price']
                    #product.description = form.cleaned_data['description']
                    #product.category = form.cleaned_data['category']
                    form.save()
                    return render(request, 'src/index.html', {'form':LibrosForm(),'Libros':Libros.objects.all()})
                else:
                    print("Invalido")
            #print("usuario: ",request.user)
            #print("usuario permisos: ",request.user.get_all_permissions())
            #print(request.user.has_perm('src.ver_zulia'))
            
            
            
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['informacion'] = "Hola..."
        if self.request.method == "GET":
            context["form"] =LibrosForm()
            context["Libros"] =Libros.objects.all()
            



################ AQUI VA LA LOGICA DE LOS PERMISOS##############
        print("Usuario get: ",self.request.user)
        
        context['usuario'] = self.request.user
        return context



def pruebas(request):


    return render(request, 'pruebas.html', {})




###### APIS ##########




def api_login(request):


    if request.method == 'GET':


        datos={'saludo':'prueba','despedida':'Adios'}
        return JsonResponse(datos)


def PasarDatos(request):

    return response("datos")

src/templates/src/EliminarLibro.html
{% extends "base.html" %}
{% load static %}

{% block EnlacesPersonalizados %}

<link rel="stylesheet" href="{% static 'src/css/login.css' %}">

<style>
  .abs-center {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
}

</style>


{% endblock %}

{% block titulo %}Login{% endblock %}

{% block contenedor %}


<section class="content-header">
    <div class="container-fluid">
     
        <h1 class="text-center">{{titulo}}</h1>
     
    </div>
  </section>
<!------------------------------------------ Aqui Empieza el contenido ------------------------------------------------------>
  <section class="content-header">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-sm-7">
      <div class="card">
        
        <div class="card-body">
            <form action="#" method="POST" >
                {% csrf_token %}

                        <div class="row">

                            <div class="col mb-3">
                                <h6>Estas seguro de borrar el Libro {{object.nombre}}?</h6>
                            </div>



                                
                            
                        </div>

                        

                      
                   

                    <br>


                    <div class="row justify-content-center">
                        
                        <div class="col-md-4">
                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-primary">Confirmar</button>
                                <a href="{% url 'src:index' %}" class="btn btn-danger">Cancelar</a>
                              </div>
                           </div>
                      </div>
                    
                    

            </form>
            
        </div>
      </div>
    </div>
</div>
    </div>
  </section>




{% endblock %}

src/templates/src/index.html
{% extends "base.html" %}

{% load static %}

{% block EnlacesPersonalizados %}
    
<!-- ======= Icons used for dropdown (you can use your own) ======== -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">



    

{% endblock %}

{% block titulo %}Index{% endblock %}

{% block contenedor %}



<div class="container ">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Biblioteca</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'src:index' %}" >
                Home
              </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Link
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
              <li><a class="dropdown-item" href="#">accion1</a></li>
              <li><a class="dropdown-item" href="#">accion2</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">accion3</a></li>
            </ul>
          </li>
        </ul>
        <form class="d-flex">
         <button class="btn btn-outline-success"><a href="{% url 'src:logout' %}">Salir</a></button>
        </form>
      </div>
    </div>
  </nav>

  <div class="row">
    <div class="col-sm-4 border">
      
      <h3>Registrar Libro</h3>
      <form action="#" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
     </form>


    </div>
    <div class="col-sm-8 border">
      <h3>Lista de Libros</h3>
      <hr>
      {% for libro in Libros %}
        <ul>
          <li>Nombre Libro: {{libro.nombre}}</li>
          <li>Nombre Autor: {{libro.autor}}</li>
          <li><a href="{% url 'src:Libro_eliminar' libro.id %}" class="btn btn-danger" title="Delete"><i class="bi bi-trash-fill"></i></a></li>
        </ul>
        <hr>
      {% endfor %}
    </div>
  </div>

</div><!---fin de container--->



{% endblock %}


{% block EnlacesListado_js %}




  

{% endblock %}

src/templates/src/login.html
{% extends "base.html" %}
{% load static %}

{% block EnlacesPersonalizados %}

<link rel="stylesheet" href="{% static 'src/css/login.css' %}">

<style>
  .abs-center {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
}

</style>


{% endblock %}

{% block titulo %}Login{% endblock %}

{% block contenedor %}



<div class="container  ">
    <div class="row justify-content-center ">
      <div class="col-md-3 offset-m-3  abs-center ">
        
        <div class=" card border border-dark ">

            <form action="{% url 'src:login' %}" class="card-body cardbody-color  bg-dark" method="post">

              {% csrf_token %}
            <div class="text-center">
              <img id="imagenLogin" src="{% static 'src/img/logo_login_libro.jpg' %}" class="img-fluid profile-image-pic img-thumbnail rounded-circle my-2">
            </div>
            
            
              {% if messages %} 
              <div class="alert alert-danger ">
                 {% for message in messages %} {{ message }} {% endfor %} 

              </div>
              {% endif %}

            
    

                {% if form.errors %}
                    
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

            <div class="mb-3">
                {{form.username}}
            </div>
            <div class="mb-3">
              {{form.password}}
            </div>
            <div class="text-center"><button type="submit" class="btn btn-outline-secondary text-white px-5  ">Iniciar Sesion</button></div>
            <div class="text-center">
              <a href="{% url 'src:registrar' %}">
                <input type="button" class="btn btn-outline-secondary text-white px-5  " value="Registrar">
              </a>
        </div>
            
          </form>

          
        </div>

      </div>
    </div>
  </div>




{% endblock %}

src/templates/src/registrarUsuario.html
{% extends "base.html" %}
{% load static %}

{% block EnlacesPersonalizados %}

<link rel="stylesheet" href="{% static 'src/css/login.css' %}">

<style>
  .abs-center {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
}

</style>


{% endblock %}

{% block titulo %}Login{% endblock %}

{% block contenedor %}



<div class="container  ">
    <div class="row justify-content-center ">
      <div class="col-md-5 offset-m-3  abs-center ">
        
        <div class=" card border border-dark ">

            <form action="#" class="card-body cardbody-color  bg-white" method="post">

              {% csrf_token %}
            <div class="text-center">
              <img id="imagenLogin" src="{% static 'src/img/logo_login_libro.jpg' %}" class="img-fluid profile-image-pic img-thumbnail rounded-circle my-2">
            </div>
            
            
              {% if messages %} 
              <div class="alert alert-danger ">
                 {% for message in messages %} {{ message }} {% endfor %} 

              </div>
              {% endif %}

            
    

                {% if form.errors %}
                    
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

            <div class="mb-3">
                {{form.as_p}}
            </div>
            <div class="text-center"><button type="submit" class="btn  text-black px-5  ">Iniciar Sesion</button></div>
            
          </form>

          
        </div>

      </div>
    </div>
  </div>




{% endblock %}